sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t sebastianalbers/rpi-gitea .
# test image
- docker run sebastianalbers/rpi-gitea /app/gitea/gitea --version
after_success:
# trigger latest build on Docker Hub
- curl -X POST "$DOCKER_HUB_TRIGGER_URL"
# tag Docker image with version and push to Docker Hub
- gitea_version=$(docker run sebastianalbers/rpi-gitea /app/gitea/gitea --version |
    sed 's/^Gitea version \([0-9\.]*\) .*$/\1/')
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker tag "sebastianalbers/rpi-gitea:latest" "sebastianalbers/rpi-gitea:${gitea_version}"
- docker push "sebastianalbers/rpi-gitea:${gitea_version}"

