#!/bin/bash

set -euxo pipefail

# push latest arm32v7 and arm64v8 images
docker push "sebastianalbers/gitea:latest-arm32v7"
docker push "sebastianalbers/gitea:latest-arm64v8"

# read version from Docker container
version=$(./read-version.sh amd64)

# push multi-arch image
./push-multi-arch-image.sh "${version}"
